version: 2.1
jobs:
 deploy:
 docker:
 - image: cimg/aws:2023.04.1
 steps:
 - checkout
 - run:
 name: Deploy to S3
 command: aws s3 sync .s3://first-project4593/
workflows:
 Production:
 jobs:
 - deploy:
 filters:
 branches:
 only: main
